---
resources:
- name: repo
  type: git
  source:
    uri: git@github.com:dolph/go-skeleton.git
    branch: master
    private_key: {{ssh_private_key}}

jobs:
- name: test
  serial: false
  build_logs_to_retain: 10
  plan:
  - get: repo
    trigger: true
  - task: test
    timeout: 5m
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: dolphm/ubuntu-google-cloud
      inputs:
      - name: repo
      run:
        path: repo/ci/test.sh
- name: deploy
  serial: true
  build_logs_to_retain: 10
  plan:
  - get: repo
    trigger: true
    passed: [test]
  - task: run
    timeout: 15m
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: dolphm/ubuntu-google-cloud
      inputs:
      - name: repo
      run:
        path: repo/ci/deploy.sh
        args:
        - go-skeleton
        - {{go_skeleton_deploy_key}}
- name: smoke-test
  serial: true
  build_logs_to_retain: 10
  plan:
  - get: repo
    trigger: true
    passed: [deploy]
  - task: smoke
    timeout: 5m
    attempts: 1
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: dolphm/network-tools
      inputs:
      - name: repo
      run:
        path: repo/ci/smoke.sh
        args:
        - go-skeleton.appspot.com
